let date = new Date();
console.log(date);
console.log(date.getDate());
console.log(date.toDateString());
console.log(date.toTimeString());
var dt = new Date("Aug 21, 2023 11:24:06");
console.log(dt);
const d = new Date("2015-03-24");
console.log(d);
const dd = new Date("05/23/1997");
console.log(dd);
const ddd = new Date("21 Oct 2020");
console.log(ddd);